db:
  url: mongodb://localhost:27017/test
markets:
  history: 300d
betting:
  amount: 2.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      tomcat: false
      jvm: false
      process: false
      hikaricp: false
      system: false
      jdbc: false
      logback: false