db:
  file:
markets:
  history: 300d
  lookAhead: 7d
betting:
  amount: 2.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      tomcat: false
      jvm: false
      process: false
      hikaricp: false
      system: false
      jdbc: false
      logback: false