package cz.fb.manaus.core

object MarketCategories {
    const val SOCCER = "soccer"
    const val ESPORTS = "esports"
    const val TABLE_TENNIS = "tableTennis"
    const val TENNIS = "tennis"
    const val ALL = "_all_"
    const val BASKETBALL = "basketball"
    const val BASEBALL = "baseball"
    const val AMERICAN_FOOTBALL = "americanFootball"
    const val RUGBY = "rugby"
    const val GOLF = "golf"
    const val CRICKET = "cricket"
    const val ICE_HOCKEY = "iceHockey"
    const val VOLLEYBALL = "volleyball"
    const val HANDBALL = "handball"
    const val HORSES = "horses"
    const val MOTOR_SPORT = "motorSport"
    const val GREY_HOUNDS = "greyHounds"
    const val POLITICS = "politics"
    const val CYCLING = "cycling"
    const val FINANCIAL = "financial"
    const val SNOOKER = "snooker"
}
