market-runner:
  runnerName:
  types:
    - three_way
    - match_odds
    - rt_match_odds
    - moneyline
price:
  downgradeBackProposerBackPrice: 0.1
  downgradeBackProposerLayPrice: 0.1
  downgradeLayProposerBackPrice: 0.1
  downgradeLayProposerLayPrice: 0.1
  bulldoze: 10
  limit: 3
  min: 1.0
  max: 1000
