market-runner:
  runnerName:
  types:
    - three_way
    - match_odds
    - rt_match_odds
    - moneyline
price:
  downgradeBackRate: 0.1
  downgradeLayRate: 0.1
  bulldoze: 10
  limit: 3
  min: 1.0
  max: 1000
